import turtle
window = turtle.Screen()
lilguy = turtle.Turtle()
lilguy.shape("turtle")
lilguy.color("purple")
window.bgcolor("white")
lilguy.forward(50)
lilguy.right(90)
lilguy.forward(50)
lilguy.right(90)
lilguy.forward(50)
lilguy.right(90)
lilguy.forward(50)

lilguy.up()
lilguy.forward(25)  
lilguy.down()
lilguy.color("red")
lilguy.forward(50)
lilguy.right(90)
lilguy.forward(50)
lilguy.right(90)
lilguy.forward(50)
lilguy.right(90)
lilguy.forward(50)
window.exitonclick()